services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432 # make sure you don't have another container running on 5432
    environment:
      - POSTGRES_DB=odin_db
      - POSTGRES_USER=parthkal
      - POSTGRES_PASSWORD=yolo1712

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
